service: todos-frontend
runtime: nodejs
env: flex

resources:
  cpu: 0.5
  memory_gb: 0.5

manual_scaling:
  instances: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /(api|_ah)/.*
  script: app
- url: /
  static_dir: dist

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?\..*$
- ^node_modules/(.*/)?
- ^src/(.*/)?
- ^public/(.*/)?
